### ISSUE TITLE
pgAdmin Runtime Environment

### ISSUE THREAD

**Issue by NoahVaknin641** [EnterpriseDB/edb-installers#166]
I just installed postgresql-17.0-rc1-windows-x64 on windows 11, everything seems to be ok during the installation, but when I execute the application pgAdmin 4 is sends me next error: 

--------------------------------------------------------
Python Path: "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\python.exe"
Runtime Config File: "C:\Users\nvak6\AppData\Roaming\pgadmin4\config.json"
Webapp Path: "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\pgAdmin4.py"
pgAdmin Command: "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\python.exe -s C:\Program Files\PostgreSQL\17\pgAdmin 4\web\pgAdmin4.py"
Environment: 
  - ALLUSERSPROFILE: C:\ProgramData
  - APPDATA: C:\Users\nvak6\AppData\Roaming
  - CommonProgramFiles: C:\Program Files\Common Files
  - CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
  - CommonProgramW6432: C:\Program Files\Common Files
  - COMPUTERNAME: NOAHPC
  - ComSpec: C:\WINDOWS\system32\cmd.exe
  - DriverData: C:\Windows\System32\Drivers\DriverData
  - EFC_12540: 1
  - ELECTRON_ENABLE_SECURITY_WARNINGS: false
  - HOMEDRIVE: C:
  - HOMEPATH: \Users\nvak6
  - IGCCSVC_DB: AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAoRqQxFHeg0GwYq5iVWStAwQAAAACAAAAAAAQZgAAAAEAACAAAAA+o367R1jU3VgSxuoZCQPA44gM2ZmD95PWUesoj8vkvQAAAAAOgAAAAAIAACAAAAA8Q+h+uyES3OVcdrLFo2oEgXzbbB9DcmK/gDAv6F6HjWAAAACWfONIdSAE3KpwafDySUCFwNdCh/YIU8K54Xcf0p5M1Z/1nZtG8l/DvkLZWoHoBwwAOVsbO0SsR+Sn6cgYDUZOL0G5UiJED1oEPMa0D+vbgYnIwxSwJ9JXV/qWqgA5/rVAAAAAYuiraKBM6hu5iMgYWZ1Y+rjyESKBZjRy0j0XAibQDPObTEahIzOztBsFRj5TL7wko1ilCNwsN6pckRfJBEtUww==
  - LOCALAPPDATA: C:\Users\nvak6\AppData\Local
  - LOGONSERVER: \\NOAHPC
  - NUMBER_OF_PROCESSORS: 12
  - OneDrive: C:\Users\nvak6\OneDrive
  - OneDriveConsumer: C:\Users\nvak6\OneDrive
  - ORIGINAL_XDG_CURRENT_DESKTOP: undefined
  - OS: Windows_NT
  - Path: C:\Program Files\PostgreSQL\17\pgAdmin 4\runtime;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\nvak6\AppData\Local\Microsoft\WindowsApps;C:\Users\nvak6\AppData\Roaming\TinyTeX\bin\windows
  - PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
  - PGADMIN_INT_KEY: 08a5949e-e244-442a-83d7-4638f8d6431a
  - PGADMIN_INT_PORT: 53967
  - PGADMIN_SERVER_MODE: OFF
  - PROCESSOR_ARCHITECTURE: AMD64
  - PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 154 Stepping 4, GenuineIntel
  - PROCESSOR_LEVEL: 6
  - PROCESSOR_REVISION: 9a04
  - ProgramData: C:\ProgramData
  - ProgramFiles: C:\Program Files
  - ProgramFiles(x86): C:\Program Files (x86)
  - ProgramW6432: C:\Program Files
  - PSModulePath: C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
  - PUBLIC: C:\Users\Public
  - SESSIONNAME: Console
  - SystemDrive: C:
  - SystemRoot: C:\WINDOWS
  - TEMP: C:\Users\nvak6\AppData\Local\Temp
  - TMP: C:\Users\nvak6\AppData\Local\Temp
  - USERDOMAIN: NOAHPC
  - USERDOMAIN_ROAMINGPROFILE: NOAHPC
  - USERNAME: nvak6
  - USERPROFILE: C:\Users\nvak6
  - windir: C:\WINDOWS
  - ZES_ENABLE_SYSMAN: 1
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.008 Sec
2024-09-24 13:03:55,701: ERROR	pgadmin:	Table(s) ['query_history', 'database', 'sharedserver', 'macros', 'user_macros', 'user_mfa'] are missing in the database
Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\pgAdmin4.py", line 103, in <module>

    app = create_app()
          ^^^^^^^^^^^^
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\pgadmin\__init__.py", line 473, in create_app
    run_migration_for_sqlite()
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\pgadmin\__init__.py", line 440, in run_migration_for_sqlite
    backup_db_file()
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\pgadmin\__init__.py", line 368, in backup_db_file
    os.rename(SQLITE_PATH, backup_file_name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\nvak6\\AppData\\Roaming\\pgAdmin\\pgadmin4.db' -> 'C:\\Users\\nvak6\\AppData\\Roaming\\pgAdmin\\pgadmin4.db.20240924130355'

**Comment by NoahVaknin641** [comment]
Ive already tried the following:
Close All pgAdmin Instances: Ensure that no other instances of pgAdmin are running. You can check this in the Task Manager and end any pgAdmin processes.
Restart Your Computer: Sometimes, a simple restart can free up the file that is being used by another process.
Check for Background Processes: Make sure no background processes are using the pgadmin4.db file. You can use tools like Process Explorer to identify which process is locking the file.
Rename the File Manually: o Navigate to C:\Users\nvak6\AppData\Roaming\pgAdmin. o Try renaming the pgadmin4.db file manually to something like pgadmin4.db.old.
Run pgAdmin as Administrator: Right-click on the pgAdmin shortcut and select “Run as administrator” to ensure it has the necessary permissions.
Check File Permissions: Ensure that your user account has full control over the pgadmin4.db file. Right-click the file, go to Properties > Security, and adjust the permissions if necessary.

**Comment by sandeep-edb** [comment]
Hi,
The issue should be fixed in the PostgreSQL 17.0 that is released yesterday. Could you please try that?

**Comment by NoahVaknin641** [comment]
Is it the 17.01 version?

**Comment by NoahVaknin641** [comment]
I’m still getting the same error message I just downloaded it

**Comment by akshay-joshi** [comment]
@NoahVaknin641

I have installed the latest PostgreSQL 17 on Windows 11, and pgAdmin 4 is working smoothly. If the "pgadmin4.db" file already exists, please delete it before launching pgAdmin 4.

<img width="1410" alt="Screenshot 2024-10-01 at 4 29 22 PM" src="https://github.com/user-attachments/assets/361221be-ff74-4eeb-b091-86ece3e044a6">
