### ISSUE TITLE
Install Error- Database Cluster Initialisation Failed - Windows 10

### ISSUE THREAD

**Issue by fabulous-fabio** [EnterpriseDB/edb-installers#179]
Hello,
When trying to install Postgres using the provided installer, I keep encountering the following error:

I've already attempted using different versions of the installer, but the same issue occurs every time.

![67bf2ad8-cd4c-4ed0-bef6-145a43becf13](https://github.com/user-attachments/assets/45f462e1-b534-4313-b0c1-da1ffec03743)

Has anyone else experienced this problem or knows what might be causing it? I'm feeling quite stuck at this point.

Kind regards,
Fabio

**Comment by Im1Bear** [comment]
I have the same Issue, tried changing the Language for the Installation but didn't change a thing, I tried following a [Stackoverflow](https://stackoverflow.com/questions/32453451/postgres-installation-the-database-cluster-initialization-failed-postgresql-ve) Post, but also didn't work.

**Comment by sandeep-edb** [comment]
Hi,
Could you please share the installer filename? Also, if you can share the installation log file that must have created by the installer in system TEMP location?

**Comment by Im1Bear** [comment]
> Hi, Could you please share the installer filename? Also, if you can share the installation log file that must have created by the installer in system TEMP location?

[install-postgresql.log](https://github.com/user-attachments/files/17505009/install-postgresql.log)

**Comment by sandeep-edb** [comment]
Thanks, I checked the log and observed that it's German OS. Is that correct? I'm guessing the default service account that the installer uses to run the postgres service "NT AUTHORITY\NetworkService" doesn't exist on your system. It must be something else. 

Could you try running the installer EXE on the command prompt with the option "--serviceaccount <the_name_that_exist_for_networkservice> ?

**Comment by Im1Bear** [comment]
Yes, the German OS is correct, 
I've tried running the EXE with Powershell, 
`Start-Process C:\Users\Admin\Downloads\postgresql-17.0-1-windows-x64.exe --serviceaccount`
but it doesn't work (with the Name).

**Comment by sandeep-edb** [comment]
OK, could you share the installation log so I see if it made any difference? 

Also, if you could share the output of the command:
`wmic sysaccount where SID="S-1-5-20" get name`

**Comment by Im1Bear** [comment]
The Logs didn't change.

Output for the Command:
Invalid parameter for this level.
Doesn't change if I use any other Terminal or change Folder Location. Maybe someone else can give more insight?

**Comment by sandeep-edb** [comment]
You mean you tried the 
`Start-Process C:\Users\Admin\Downloads\postgresql-17.0-1-windows-x64.exe --serviceaccount <snetworkservice_account_name_on_your_os>` ? Please share the installation log of this.

**Comment by moerwald** [comment]
@Im1Bear did you catch this log-entry?

> CScript-Fehler: Der Zugriff auf Windows Script Host wurde fr diesem Computer deaktiviert. Wenden Sie sich an Ihren Administrator, um weitere Details in Erfahrung zu bringen.

**Comment by Im1Bear** [comment]
I am currently not at home and will get in touch later.

**Comment by Im1Bear** [comment]
> @Im1Bear did you catch this log-entry?
> 
> > CScript-Fehler: Der Zugriff auf Windows Script Host wurde f�r diesem Computer deaktiviert. Wenden Sie sich an Ihren Administrator, um weitere Details in Erfahrung zu bringen.

Yes, I get this message daily, because I deactivated Windows Script Host.
I've now activated it.
I'm no longer considering using PostgreSQL and now use MongoDB, because of Issues like this, if I need more help to install something like PostgreSQL, rather than developing something with it, I simply won't use it.
Furthermore, I'm still open to helping with issues currently open, but I'm not going to use PostgreSQL.


> You mean you tried the `Start-Process C:\Users\Admin\Downloads\postgresql-17.0-1-windows-x64.exe --serviceaccount <snetworkservice_account_name_on_your_os>` ? Please share the installation log of this.

I've tried using this Command, with any Username I could imagine, it just didn't work.

**Comment by yunofsea** [comment]
Hi,I encountered this porblem today,and I fixed it by choosing the locale "English US"

**Comment by sandeep-edb** [comment]
The PostgreSQL 17.2-2, 16.6-2, 15.10-2 are available for download. These installers include a fix for system installation issue.

**Comment by surebrec** [comment]
the error is still being reproduced in Win 10 [postgresql-17.2-3-windows-x64.exe]

`ўлЇ®«­пҐвбп § Є«озЁвҐ«м­ п Ё­ЁжЁ «Ё§ жЁп... 2024-12-18 13:41:03.511 MSK [644] FATAL:  invalid byte sequence for encoding "UTF8": 0xe7 0xf4 0xfb`

[install-postgresql.log](https://github.com/user-attachments/files/18180601/install-postgresql.log)

**Comment by sandeep-edb** [comment]
The latest PostgreSQL minor releases for the installers with the fix are now available for download. Closing the ticket. Thanks for your patience.

**Comment by janmejaysahoo77** [comment]
i have downloaded postgress 18 still it is showing same issue

**Comment by imyatin23** [comment]
Hi all, I am trying to install version 18 and getting the same error. Could this be related to the privilages? The machine I am trying to install postgres on is corporate and I do not have Full Control on C drive. I have something called Elevated Privilages. I tried choosing US as a locale. Thank you in advance.
