### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DTN87** [EnterpriseDB/edb-installers#222]
Hello,

I get the following error. My username and password are correct.

![image](https://github.com/user-attachments/assets/ce0e8465-f9f3-4d80-8ce2-e2c5d4a615b4)
[Line 8 error.pdf](https://github.com/user-attachments/files/18327139/Line.8.error.pdf)

**Comment by sandeep-edb** [comment]
Hi,
what's the installer filename? could you also share the installation log that would have created in system temp location?

**Comment by DTN87** [comment]
Hi Sandeep,

It happened during the installation process. I entered my username and
password, then hit next and immediately got an alert that read as follows.
See the screenshot below as well. I hope my explanation helps.

psql: ERROR: column d.daticulocale does not exist
LINE 8: d.daticulocale as "ICU Locale",
      ^
HINT: Perhaps you meant to reference the column "d.datlocale"

[image: image.png]

**Comment by sandeep-edb** [comment]
Thanks for the details. Is this the postgresql installer file or pgbouncer installer?

**Comment by DTN87** [comment]
It's the former. I ended up having to skip this part, but I think it should
have been completed.

**Comment by sandeep-edb** [comment]
so you installed PostgreSQL and at the end of installation, launched StackBuilder to download any other installer?

**Comment by 78zhanghao87** [comment]
same issues when StackBuilder install pgBouncer V1.23.1-1

**Comment by aland-semperis** [comment]
Also have issue with pgBouncer v1.23.1-1

![Image](https://github.com/user-attachments/assets/15e1e1b4-2043-4eec-8a5c-9c21bbd52364)

**Comment by sandeep-edb** [comment]
We are working on a fix. The update to the installer should be available early next week

**Comment by sandeep-edb** [comment]
Please note the fix is available in pgBouncer 1.24.0 that is available for download through StackBuilder

**Comment by DTN87** [comment]
Thank you, Sandeep!

**Comment by Pummelchen** [comment]
This bug is not fixed. Same pgBouncer bug.

System
Macbook Pro M3 15.4.1
First installation of PosgreSQL 17.4-2

Stack Builder 4.2.2 fails to install pgBouncer 1.24.1-1

<img width="1018" alt="Image" src="https://github.com/user-attachments/assets/0109694a-11e5-46f2-827b-8d322125d314" />

**Comment by sandeep-edb** [comment]
This is a different error than than reported earlier. This error means the psql was able to connect to the database using the given inputs. Please reconfirm your PostgreSQL installation details

**Comment by Pummelchen** [comment]
Details:
Macbook Pro M3 15.4.1
First installation of PosgreSQL 17.4-2
Stack Builder 4.2.2 fails to install pgBouncer 1.24.1-1

I can log into the Admin panel (pgAdmin 4) without problems and see the database.
